# Generated by Django 3.2 on 2022-10-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(0, '!'), (1, '!!'), (2, '!!!')], default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[(0, 'ToDo'), (1, 'In Progress'), (2, 'Done')], default=0, max_length=12),
        ),
    ]
