# Generated by Django 3.2 on 2022-10-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20221014_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('!', '!'), ('!!', '!!'), ('!!!', '!!!')], default='!', max_length=12),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ToDo', 'ToDo'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='ToDo', max_length=12),
        ),
    ]
